import { type Report } from './types'

export const MOCK_REPORTS: Report[] = [
  {
    id: 'design-is-the-exploit',
    title: 'Design is the Exploit',
    description:
      'Why Web3\'s biggest systemic risk isn\'t a zero-day — it\'s the interface. An argument for why current Web3 design is the single biggest systemic risk to mass adoption.',
    type: 'Research',
    access: 'free',
    likes: 847,
    downloads: 3200,
    author: 'aldidstn',
    authorAddress: '0xaldi000000000000',
    createdAt: '2026-03-24T08:00:00Z',
    onChain: true,
    fileType: 'md',
    tags: ['UX', 'Security', 'Design', 'Web3', 'Blind Signing'],
    blobAccount: 'aldidstn',
    blobName: 'design-is-the-exploit.md',
  },
  {
    id: '1',
    title: 'Aptos DeFi Ecosystem Overview Q1 2026',
    description: 'A comprehensive overview of the Aptos DeFi landscape including TVL trends, top protocols, and user growth metrics.',
    type: 'Research',
    access: 'free',
    likes: 312,
    downloads: 1480,
    author: 'shelby.apt',
    authorAddress: '0x1a2b3c4d5e6f',
    createdAt: '2026-03-10T08:00:00Z',
    onChain: true,
    fileType: 'pdf',
    tags: ['DeFi', 'Aptos', 'TVL'],
  },
  {
    id: '2',
    title: 'Intel Wallet Clustering Report',
    description: 'Identification of high-conviction wallets using on-chain clustering techniques across 90 days of transaction data.',
    type: 'Intel',
    access: 'premium',
    price: 2.5,
    likes: 891,
    downloads: 620,
    author: 'alpha.apt',
    authorAddress: '0x2b3c4d5e6f7a',
    createdAt: '2026-03-15T10:30:00Z',
    onChain: true,
    fileType: 'pdf',
    tags: ['Intel', 'Wallets', 'Clustering'],
  },
  {
    id: '3',
    title: 'Token Unlocks Calendar — March 2026',
    description: 'Full breakdown of upcoming token unlock events across the Aptos ecosystem with estimated market impact.',
    type: 'Analysis',
    access: 'free',
    likes: 204,
    downloads: 975,
    author: 'researchdao.apt',
    authorAddress: '0x3c4d5e6f7a8b',
    createdAt: '2026-03-01T06:00:00Z',
    onChain: true,
    fileType: 'csv',
    tags: ['Unlocks', 'Tokens', 'Calendar'],
  },
  {
    id: '4',
    title: 'Shelby Protocol — Technical Deep Dive',
    description: 'An in-depth technical analysis of the Shelby Protocol including architecture, blob commitments, and incentive mechanisms.',
    type: 'Document',
    access: 'free',
    likes: 543,
    downloads: 2100,
    author: 'shelby.apt',
    authorAddress: '0x1a2b3c4d5e6f',
    createdAt: '2026-02-20T12:00:00Z',
    onChain: true,
    fileType: 'md',
    tags: ['Shelby', 'Protocol', 'Technical'],
  },
  {
    id: '5',
    title: 'Whale Activity Tracker — Feb/Mar 2026',
    description: 'Detailed on-chain monitoring of wallets holding >100k APT and their recent movement patterns.',
    type: 'Intel',
    access: 'premium',
    price: 5,
    likes: 1240,
    downloads: 430,
    author: 'alpha.apt',
    authorAddress: '0x2b3c4d5e6f7a',
    createdAt: '2026-03-18T09:00:00Z',
    onChain: true,
    fileType: 'pdf',
    tags: ['Whales', 'Tracking', 'APT'],
  },
  {
    id: '6',
    title: 'Gas Fee Optimization Guide for Aptos dApps',
    description: 'Practical guide for developers to minimize gas costs when building on Aptos, with benchmarks and code examples.',
    type: 'Document',
    access: 'free',
    likes: 178,
    downloads: 890,
    author: 'devguild.apt',
    authorAddress: '0x4d5e6f7a8b9c',
    createdAt: '2026-03-05T14:00:00Z',
    onChain: false,
    fileType: 'md',
    tags: ['Gas', 'Optimization', 'Developer'],
  },
  {
    id: '7',
    title: 'Liquid Staking Derivatives Comparison',
    description: 'Side-by-side analysis of all liquid staking protocols on Aptos: yield rates, TVL, risks, and smart contract audits.',
    type: 'Analysis',
    access: 'premium',
    price: 1.5,
    likes: 667,
    downloads: 310,
    author: 'researchdao.apt',
    authorAddress: '0x3c4d5e6f7a8b',
    createdAt: '2026-03-12T11:00:00Z',
    onChain: true,
    fileType: 'pdf',
    tags: ['LSD', 'Staking', 'Yield'],
  },
  {
    id: '8',
    title: 'Cross-Chain Bridge Flow Analysis',
    description: 'Tracking capital flows between Aptos and other L1/L2 networks over 60 days, identifying macro trends.',
    type: 'Research',
    access: 'premium',
    price: 3,
    likes: 445,
    downloads: 280,
    author: 'alpha.apt',
    authorAddress: '0x2b3c4d5e6f7a',
    createdAt: '2026-03-20T07:00:00Z',
    onChain: true,
    fileType: 'json',
    tags: ['Bridge', 'Cross-chain', 'Capital Flows'],
  },
  {
    id: '9',
    title: 'NFT Market Pulse — Weekly Report',
    description: 'Weekly snapshot of NFT trading volumes, floor prices, and notable sales across Aptos marketplaces.',
    type: 'Report',
    access: 'free',
    likes: 99,
    downloads: 670,
    author: 'nftwatch.apt',
    authorAddress: '0x5e6f7a8b9c0d',
    createdAt: '2026-03-22T08:00:00Z',
    onChain: false,
    fileType: 'pdf',
    tags: ['NFT', 'Market', 'Weekly'],
  },
]
