[package]
name = "shelby-registry"
version = "1.0.0"
authors = []

[addresses]
# Replace "_" with your Aptos testnet wallet address after running:
#   aptos init --network testnet
# then:
#   aptos account list
shelby_registry = "_"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "e2550719488c2f88f8b36d19ad79bed170be124d"
subdir = "aptos-move/framework/aptos-framework"
