[package]
name = "shelby-registry"
version = "1.0.0"
authors = []

[addresses]
# Replace "_" with your Aptos testnet wallet address after running:
#   aptos init --network testnet
# then:
#   aptos account list
shelby_registry = "0x38c009595f40c6533e3ee26437b9bed0f90e72eaf0737fd41d5e575ef8d2b6f6"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "e2550719488c2f88f8b36d19ad79bed170be124d"
subdir = "aptos-move/framework/aptos-framework"
